name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./Dockerfile, ./app.py, ./requirements.txt, ./seeds, ./templates, ./static, ./data, ./lib"
          target: ~/booksnfilms

      - name: Ensure Docker network exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! "$(docker network ls -q -f name=booksnfilms_network)" ]; then
              docker network create booksnfilms_network
            fi

      - name: Ensure database is running
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! "$(docker ps -q -f name=^postgres$)" ]; then
              if [ "$(docker ps -aq -f name=^postgres$)" ]; then
                docker rm -f postgres
              fi
              docker run \
                --name postgres \
                --network booksnfilms_network \
                -e POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
                -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
                -e POSTGRES_DB='booksnfilms' \
                -d postgres:17

              sleep 2

              docker exec -i postgres psql -U ${{ secrets.POSTGRES_USER }} -d booksnfilms < ~/booksnfilms/seeds/booksnfilms.pgsql


              sleep 2
            fi

      - name: Build Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker build --pull -t booksnfilms:latest ~/booksnfilms

      - name: Deploy new container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(docker ps -q -f name=^booksnfilms$)" ]; then
              docker stop $(docker ps -q -f name=^booksnfilms$) || true
            fi
            docker rm booksnfilms || true
            docker image prune -f || true
            docker run -d \
              --name booksnfilms \
              --network booksnfilms_network \
              --restart unless-stopped \
              -p 5001:5001 \
              booksnfilms:latest
